# Generated by Django 4.0.2 on 2022-02-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='https://previews.123rf.com/images/panyamail/panyamail1809/panyamail180900207/109879013-user-avatar-icon-sign-profile-symbol.jpg?fj=1', upload_to='users/%Y/%m/%d/'),
        ),
    ]
