# Generated by Django 4.0.2 on 2022-02-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default_profile_photo.svg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
